services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - APP_ENV=development
      - CONFIG_DIR=/etc/rust_starter
    secrets:
      - source: config
        target: /etc/rust_starter/config.yml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rust-starter-network

  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - rust-starter-network

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=rust_starter
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 15432
    ports:
      - '15432:5432'
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rust-starter-network
volumes:
  db-data:

secrets:
  db-password:
    file: password.txt
  config:
    file: config/config.yml

networks:
  rust-starter-network:
    driver: bridge
