[package]
name = "configuration"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
config.workspace = true
dotenvy.workspace = true
notify.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
