[alias]
# two aliases for development and production
d = "run --quiet"
dev = "watch -q -c -x d"

# Enable in Production
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
