[package]
name = "telemetry"
edition = "2024"
version.workspace = true
license.workspace = true
description = "Telemetry and logging utilities for the Rust Starter template"

[dependencies]
# tracing
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
configuration = { workspace = true }
