[package]
name = "telemetry"
edition = "2024"
version.workspace = true
license.workspace = true
description = "Telemetry and logging utilities for the Rust Starter template"

[dependencies]
# tracing
serde = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-error = { workspace = true }
tracing-log = { workspace = true }
configuration = { workspace = true }
opentelemetry         = { workspace = true }
opentelemetry_sdk     = { workspace = true }
opentelemetry-otlp    = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
tracing-opentelemetry = { workspace = true }
