//! Core trait bounds for the generic store layer.

use chrono::{DateTime, Utc};
use sea_orm::{
    ActiveModelBehavior, ActiveModelTrait, ColumnTrait, EntityTrait, FromQueryResult,
    IntoActiveModel,
};
use uuid::Uuid;

use crate::types::{CreateFields, UpdateFields};

/// Domain-level trait generated by `#[derive(OrmEntity)]`.
///
/// Provides field accessors without leaking SeaORM internals.
/// Plugin methods return sane defaults when the field is absent.
pub trait OrmEntity: Send + Sync + Clone + 'static {
    fn id(&self) -> Uuid;
    fn created_at(&self) -> DateTime<Utc>;
    fn updated_at(&self) -> DateTime<Utc>;

    // Plugin: soft-delete
    fn deleted_at(&self) -> Option<DateTime<Utc>> {
        None
    }
    fn is_deleted(&self) -> bool {
        self.deleted_at().is_some()
    }

    // Plugin: metadata
    fn metadata(&self) -> Option<&serde_json::Value> {
        None
    }

    // Plugin: slug
    fn slug(&self) -> Option<&str> {
        None
    }
}

/// SeaORM column bindings and active-model helpers, generated by `#[derive(OrmEntity)]`.
///
/// Implementors should not write this by hand — use the derive macro.
pub trait SeaOrmModel:
    OrmEntity + IntoActiveModel<Self::ActiveModel> + FromQueryResult + 'static
{
    type Entity: EntityTrait<Model = Self>;
    type ActiveModel: ActiveModelTrait<Entity = Self::Entity> + ActiveModelBehavior + Send;
    type Column: ColumnTrait;

    fn id_column() -> Self::Column;
    fn created_at_column() -> Self::Column;
    fn updated_at_column() -> Self::Column;

    /// Build a fully-populated `ActiveModel` ready for `insert`.
    /// Entity-specific fields not in `CreateFields` are left as `NotSet`
    /// so the caller can set them after this call.
    fn new_active(id: Uuid, create: CreateFields, now: DateTime<Utc>) -> Self::ActiveModel;

    /// Apply plugin-level update fields and stamp `updated_at`.
    /// Entity-specific updates must be applied by the caller first.
    fn stamp_updated_at(active: &mut Self::ActiveModel, update: &UpdateFields, now: DateTime<Utc>);
}

/// Associates concrete entity types for a given application.
///
/// Implement this once in your app crate and pass it as the generic parameter
/// to `SeaOrmStore<S>`.
///
/// ```rust,ignore
/// pub struct Schema;
///
/// impl AppSchema for Schema {
///     // Add an associated type for every domain entity you own.
///     // Auth entities (User, Session, …) are managed by better-auth — skip them.
/// }
/// ```
///
/// The trait is intentionally left with no associated types in the base
/// definition so applications only enumerate the entities they own.
pub trait AppSchema: Send + Sync + 'static {}
